export const MOCK_COURTS = [
  {
    id: 'court_1',
    name: 'East River Park Courts',
    address: 'East River Park, New York, NY 10002',
    latitude: 40.7150,
    longitude: -73.9744,
    indoor: false,
  },
  {
    id: 'court_2',
    name: 'Riverside Park Pickleball',
    address: 'Riverside Park, New York, NY 10024',
    latitude: 40.7889,
    longitude: -73.9834,
    indoor: false,
  },
  {
    id: 'court_3',
    name: 'Hudson Yards Sports Complex',
    address: '500 W 33rd St, New York, NY 10001',
    latitude: 40.7538,
    longitude: -74.0023,
    indoor: true,
  },
  {
    id: 'court_4',
    name: 'Prospect Park Courts',
    address: 'Prospect Park, Brooklyn, NY 11215',
    latitude: 40.6602,
    longitude: -73.9690,
    indoor: false,
  },
  {
    id: 'court_5',
    name: 'Astoria Park Pickleball',
    address: 'Astoria Park, Queens, NY 11102',
    latitude: 40.7771,
    longitude: -73.9311,
    indoor: false,
  },
];

export const MOCK_GAMES = [
  {
    id: 'game_1',
    name: 'Morning Rally — East River',
    court: 'East River Park Courts',
    date: '2026-04-02',
    time: '7:00 AM',
    skillLevel: 'Intermediate',
    players: 2,
    maxPlayers: 4,
  },
  {
    id: 'game_2',
    name: 'Riverside Smash Session',
    court: 'Riverside Park Pickleball',
    date: '2026-04-03',
    time: '10:00 AM',
    skillLevel: 'Beginner',
    players: 1,
    maxPlayers: 4,
  },
  {
    id: 'game_3',
    name: 'Friday Night Doubles',
    court: 'Hudson Yards Sports Complex',
    date: '2026-04-04',
    time: '6:30 PM',
    skillLevel: 'Advanced',
    players: 3,
    maxPlayers: 4,
  },
];

export const MOCK_LEADERBOARD = [
  {
    id: 'player_1',
    name: 'Marcus Rodriguez',
    wins: 47,
    losses: 8,
    courtName: 'East River Park Courts',
    homeCourtKing: true,
  },
  {
    id: 'player_2',
    name: 'Aisha Thompson',
    wins: 39,
    losses: 12,
    courtName: 'Hudson Yards Sports Complex',
    homeCourtKing: true,
  },
  {
    id: 'player_3',
    name: 'Jordan Kim',
    wins: 31,
    losses: 15,
    courtName: 'Riverside Park Pickleball',
    homeCourtKing: false,
  },
  {
    id: 'player_4',
    name: 'Tyler Brooks',
    wins: 24,
    losses: 18,
    courtName: 'Prospect Park Courts',
    homeCourtKing: true,
  },
  {
    id: 'player_5',
    name: 'Priya Patel',
    wins: 19,
    losses: 21,
    courtName: 'Astoria Park Pickleball',
    homeCourtKing: false,
  },
];
